[feat] Add pypi github action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,15 +1,10 @@
-# This is a basic workflow to help you get started with Actions
 name: CI
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the main branch
   push:
     branches: [main]
   pull_request:
     branches: [main]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
 jobs:
@@ -18,23 +13,15 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-
       - name: Check files
         run: |
-          # Define the list of filenames you want to check
           FILES_TO_CHECK=("LICENSE" "README.md" "requirements.txt" "requirements-dev.txt" "setup.py")
-
-          # Initialize a variable to track missing files
           MISSING_FILES=()
-
-          # Check if each file exists in the root directory
           for FILE in "${FILES_TO_CHECK[@]}"; do
             if [ ! -f "$FILE" ]; then
               MISSING_FILES+=("$FILE")
             fi
           done
-
-          # Output the missing files
           if [ ${#MISSING_FILES[@]} -eq 0 ]; then
             echo "All files exist."
           else
@@ -44,7 +31,6 @@ jobs:
             done
             echo "::error::One or more files are missing."
             exit 1
-          fi
 
   linter:
     runs-on: ubuntu-latest
@@ -52,18 +38,39 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: 3.9
-
       - name: Install dependencies
-        run: |
-          pip install -r requirements-dev.txt
-
+        run: pip install -r requirements-dev.txt
       - name: Analysing the code with pylint
         run: |
           pylint --disable=trailing-whitespace,missing-class-docstring,missing-final-newline,trailing-newlines \
-                  --fail-under=9.0 \
-                  $(git ls-files '*.py') || echo "::warning::Pylint check failed, but the workflow will continue."
+                 --fail-under=9.0 \
+                 $(git ls-files '*.py') || echo "::warning::Pylint check failed, but the workflow will continue."
+
+  python-build-n-publish:
+    name: Build and publish Python distribution
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Initialize Python 3.9
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.9
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install flake8
+      - name: Lint with flake8
+        run: |
+          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+      - name: Build binary wheel and a source tarball
+        run: python setup.py sdist
+      - name: Publish distribution to PyPI
+        uses: pypa/gh-action-pypi-publish@master
+        with:
+          password: ${{ secrets.test_pypi_password }}
+          repository_url: https://upload.pypi.org/legacy/
